# Generated by Django 4.2.30 on 2026-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text='The news statement submitted by the user.')),
                ('label', models.CharField(choices=[('REAL', 'Real'), ('FAKE', 'Fake')], help_text='Predicted label: REAL or FAKE.', max_length=4)),
                ('confidence', models.FloatField(help_text='Model confidence score (0.0 – 1.0).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the prediction was made.')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
